### ISSUE TITLE
Fail to check resouces pack's update and download the updated pack.

### ISSUE THREAD

**Issue by NyteWL** [DeDiamondPro/Resourcify#37]
**Technical Information**
Resourcify version: 1.4.0+beta.1
Minecraft version: 1.20.1
Other mods (if relevant):

**Describe the bug**
I'm using Fast Better Grass that need to be updated. However, Resourcify failed to check the update of this pack. Then i try to update it manually but i fail to download it. It keeps saying “installing” and nothing happens.
![image](https://github.com/DeDiamondPro/Resourcify/assets/163705449/3f9020df-8096-4601-838d-7bf921e274ff)
![image](https://github.com/DeDiamondPro/Resourcify/assets/163705449/46661f31-267f-4a36-bb5d-f32162d08976)
![image](https://github.com/DeDiamondPro/Resourcify/assets/163705449/9240cd56-3991-451e-959e-8d272bb95386)
![image](https://github.com/DeDiamondPro/Resourcify/assets/163705449/1ffc8211-22ad-4b65-b8d1-9c47376d9ffc)

**Expected behavior**
Update the resources pack without exceptions.

**Steps to reproduce**
1. Load an outdated resources pack. 2. Click the update botton 3. Go to the pack's page and trry to update it manually.

**Additional information**
https://mclo.gs/JfiAQ4l

**Comment by DeDiamondPro** [comment]
Hi, thank you for your report,

The first issue you outlined should have been fixed in 865e1946652f55da7a95c1990e8d3a4115529483, and will be included in the next release.
The second issue when manually downloading is likely because there is already a file with the same name, causing it to fail. I will implement a fix for this for the next release.

**Comment by DeDiamondPro** [comment]
This has been fixed in 1.4.0: https://modrinth.com/mod/resourcify/versions
