### ISSUE TITLE
Add localized language translations

### ISSUE THREAD

**Issue by surfishs** [DeDiamondPro/Resourcify#5]
Not everyone is fluent in English and we need to optimize the readability of the interface for them.

**Comment by DeDiamondPro** [comment]
This is something I definitely want to do eventually but because of the amount of data displayed to the user that is dynamically fetched from the modrinth API (mainly categories) this is more challenging then it seems.
This will probably be something for after some of the new feature I am working on now are done.

**Comment by surfishs** [comment]
I look forward to that day, and by the way, since you have implemented the download and installation of material packs through the API, why can't the download of shaders (IRIS) also be made into this mod by the way.

**Comment by DeDiamondPro** [comment]
> I look forward to that day, and by the way, since you have implemented the download and installation of material packs through the API, why can't the download of shaders (IRIS) also be made into this mod by the way.

bc96ba4ee7a3a494c4ea0d1491e2793194bbf6d1

**Comment by surfishs** [comment]
> > I look forward to that day, and by the way, since you have implemented the download and installation of material packs through the API, why can't the download of shaders (IRIS) also be made into this mod by the way.
> 
> [bc96ba4](https://github.com/DeDiamondPro/Resourcify/commit/bc96ba4ee7a3a494c4ea0d1491e2793194bbf6d1)
forge is a phased out version and I suggest you go for this feature for fabric's Iris Shaders.

**Comment by DeDiamondPro** [comment]
> forge is a phased out version and I suggest you go for this feature for fabric's Iris Shaders.

The commit I sent (bc96ba4ee7a3a494c4ea0d1491e2793194bbf6d1) is for Iris shaders (on fabric) and was added 3 days ago
Forge/Optifine has been added like an hour ago. While I agree a lot of creators are switching to fabric, forge is not "phased out" at all when it comes to content mods and that's why I will continue to support it for the foreseeable future.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
Yeah, I want it too!

**Comment by DeDiamondPro** [comment]
This will probably be added when modrinth adds localization support, which I know they are working on.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> This will probably be added when modrinth adds localization support, which I know they are working on.

Yeah, I'm waiting for it too.

**Comment by DeDiamondPro** [comment]
Support for localizations has been added in 7e341d43edb70f2bd8b214b5262c50373d581b20, if you would like to contribute localizations you can do so by creating a new file in [src/main/resources/assets/resourcify/lang](https://github.com/DeDiamondPro/Resourcify/tree/master/src/main/resources/assets/resourcify/lang) with the file name `<language_code>.json` (you can find the language code in [the wiki](https://minecraft.wiki/w/Language) in the locale code in-game column). Then you can translate the strings from the `en_us.json` file into the language you want to translate to. If you don't have the time to translate everything partial translations are also welcome!
