### ISSUE TITLE
Other sites suppport

### ISSUE THREAD

**Issue by IZeeXeS** [DeDiamondPro/Resourcify#8]
Like Curseforge or PlanetMinecraft (if this possible)

**Comment by DeDiamondPro** [comment]
Curseforge could be done but is more complicated then modrinth since it requires me to apply for an API key and proxy all requests through my server. Additionally curseforge's filters for shaders and datapacks are... weird at best. This might be done in the future but I can't promise anything since it is possible curseforge doesn't even give me an API key.

PlanetMinecraft is unfortunately not possible since they do not have any sort of public API.

**Comment by oxodao** [comment]
Probably not that legal but does the job without api key
https://curse.tools/

**Comment by DeDiamondPro** [comment]
> Probably not that legal but does the job without api key https://curse.tools/

Yeah this is... sketchy at best and I do not feel comfortable using something like this since I:
1. Don't know what data it collects (no privacy policy of any kind)
2. Could be gone at any time because it is:
  a. Shut down by curseforge; or
  b. Whoever operates it no longer wants to/can

**Comment by DeDiamondPro** [comment]
Good news! I have received a CurseForge API key and will start working on adding support to CurseForge (and maybe also some other services) soon!

**Comment by DeDiamondPro** [comment]
👀 
![image](https://github.com/DeDiamondPro/Resourcify/assets/67508414/e0b23729-1d98-4e44-afa9-5e9a3df0e2ba)
